######################## default configuration ####################
baseURL = "https://demo.gethugothemes.com/restaurant/examplesite/"
languageCode = "en-us"
title = "Alreef Alshami Restaurant"
theme = "restaurant-hugo"
summaryLength = 10
pagination.pagerSize = 4
defaultContentLanguage = "en"
